const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.DrawingCanvas,
		C3.Behaviors.Tween,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Plugins.NinePatch,
		C3.Plugins.Particles,
		C3.Plugins.Keyboard,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Fade,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.TextBox,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.NinePatch.Acts.SetSize,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.DrawingCanvas.Acts.SetInstanceVar,
		C3.Plugins.DrawingCanvas.Acts.SetSize,
		C3.Plugins.DrawingCanvas.Acts.PasteObject,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.NinePatch.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.DrawingCanvas.Acts.MoveToTop,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.DrawingCanvas.Exps.Angle,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.DrawingCanvas.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.NinePatch.Cnds.PickByUID,
		C3.Plugins.NinePatch.Acts.SetBoolInstanceVar,
		C3.Plugins.DrawingCanvas.Acts.SetBoolInstanceVar,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.NinePatch.Cnds.PickDistance,
		C3.Plugins.DrawingCanvas.Exps.X,
		C3.Plugins.DrawingCanvas.Exps.Y,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.NinePatch.Exps.X,
		C3.Plugins.NinePatch.Exps.Y,
		C3.Plugins.NinePatch.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.NinePatch.Exps.UID,
		C3.Plugins.DrawingCanvas.Acts.SetPos,
		C3.Plugins.DrawingCanvas.Exps.Width,
		C3.Plugins.DrawingCanvas.Exps.Height,
		C3.Plugins.DrawingCanvas.Acts.MoveToBottom,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.DrawingCanvas.Exps.Count,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.System.Acts.SetLayoutAngle,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Exps.ImageOffsetY,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.TextBox.Acts.SetVisible,
		C3.Plugins.TextBox.Cnds.CompareText,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Touch.Cnds.OnTapGestureObject
	];
};
self.C3_JsPropNameTable = [
	{Index: 0},
	{Snapped: 0},
	{GridBlockUID: 0},
	{Tween: 0},
	{DragDrop: 0},
	{Piece: 0},
	{SourceImage: 0},
	{Background: 0},
	{GridBlock: 0},
	{PickEffect: 0},
	{GameManager: 0},
	{SplashGlow: 0},
	{Flash: 0},
	{WinGlow: 0},
	{Frame: 0},
	{Keyboard: 0},
	{Fade: 0},
	{Tutorial: 0},
	{quadrinho: 0},
	{frases: 0},
	{caixa_texto: 0},
	{Sprite: 0},
	{Touch: 0},
	{TextInput: 0},
	{confirmar: 0},
	{PiecesPerLine: 0},
	{PiecesWidth: 0},
	{PiecesHeight: 0},
	{SpawnMargin: 0},
	{SnapDistance: 0},
	{senha_numero: 0},
	{CurrentIndex: 0},
	{Count: 0},
	{Duration: 0},
	{Strength: 0},
	{OffsetSpeed: 0},
	{fase: 0}
];

self.InstanceType = {
	Piece: class extends self.IDrawingCanvasInstance {},
	SourceImage: class extends self.ISpriteInstance {},
	Background: class extends self.ITiledBackgroundInstance {},
	GridBlock: class extends self.I9PatchInstance {},
	PickEffect: class extends self.I9PatchInstance {},
	GameManager: class extends self.ISpriteInstance {},
	SplashGlow: class extends self.IParticlesInstance {},
	Flash: class extends self.ITiledBackgroundInstance {},
	WinGlow: class extends self.IParticlesInstance {},
	Frame: class extends self.I9PatchInstance {},
	Keyboard: class extends self.IInstance {},
	Tutorial: class extends self.ISpriteFontInstance {},
	quadrinho: class extends self.ISpriteInstance {},
	frases: class extends self.ITextInstance {},
	caixa_texto: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	TextInput: class extends self.ITextInputInstance {},
	confirmar: class extends self.ISpriteInstance {}
}